### ISSUE TITLE
Spike zeroheight as storefront

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1045]
Check out [Zeroheight](https://zeroheight.com/) as an alternative to storefront solution. 

Things to test so far:
- [x] Checkout if figma integration is possible with figma org and SSO
- [x] Checkout if storybook integration is possible using links from: https://eds-storybook-react.azurewebsites.net

[Testing environment](https://zeroheight.com/3a1fca684/p/6621e2-equinor-design-system-eds)

**Comment by lucasveil** [comment]
@mimarz  og @lucasveil  har vært i møte med en i Bouvet som vist oss rundt zero height.

**Hva er bra?**

- rask og enkelt å ta i bruk
- støtte integrasjon fra figma
- støtte integrasjon fra storybook
- utenom den navigasjon side sheet er det veldig mye frihet å custom ting (font, farge osw…)
- har versjon historikk
- kan gjemme sider (draft mode)

**Ikke så bra?**

- blir veldig dyrt siden det koster 49 dollars/ bruker
- vett ikke hvis det støtte EDS figma (skal teste i løp av uke)
- initiell sidelast virker litt tregt, når løsningen vokser virker det som


![02_styling of page](https://user-images.githubusercontent.com/65652493/105002658-efeb3a80-5a31-11eb-9c84-3c4e0932a5d9.png)
![03_mockup place holder](https://user-images.githubusercontent.com/65652493/105002667-f37ec180-5a31-11eb-8f95-07ac96e1164b.png)
![04_mockup component](https://user-images.githubusercontent.com/65652493/105002674-f4175800-5a31-11eb-86e0-bb4085b3d290.png)
![06_mockup usage](https://user-images.githubusercontent.com/65652493/105002676-f4afee80-5a31-11eb-9b69-c1004359e8c0.png)
![01_front page](https://user-images.githubusercontent.com/65652493/105002677-f5488500-5a31-11eb-96ac-e5e8d7cc5b3a.png)
![05_mockup component code](https://user-images.githubusercontent.com/65652493/105002678-f5e11b80-5a31-11eb-8c67-4046bc2b9ada.png)
![08_update figma file](https://user-images.githubusercontent.com/65652493/105002679-f679b200-5a31-11eb-8be4-dd6e54305ec8.png)
![07_component overview](https://user-images.githubusercontent.com/65652493/105002684-f679b200-5a31-11eb-80e2-c9f99ed1f6b0.png)

**Comment by wenche** [comment]
We made a [simple demo using Zeroheight](https://zeroheight.com/3xlwst8/p/507ba7-storybook/t/052660), and copy'n pasted content from the Storefront along with examples from storybook and Figma. The idea was to just give a spin, and see how the integrations worked out.

**Comment by wenche** [comment]
**Figma**

Plays nice with EDS Figma. In the `Manage` tab you'll just add the url to Figma and authorize Zeroheight with read permissions. 
![Skjermbilde 2021-01-28 kl  13 34 02](https://user-images.githubusercontent.com/1568252/106139249-7d830480-616d-11eb-9127-cc352aa71e12.png)
Then all the Figma stuff is automagically added to a hierarchical structure which makes it possible to add one or multiple Figma integrations. You can add both on folder level or individual item.
![Skjermbilde 2021-01-28 kl  13 35 56](https://user-images.githubusercontent.com/1568252/106139466-c2a73680-616d-11eb-8c08-ac5af8aae49d.png)
In the edit mode of Zeroheight you'll have some more information about each item from Figma.
![Skjermbilde 2021-01-28 kl  13 40 21](https://user-images.githubusercontent.com/1568252/106139983-73add100-616e-11eb-8edf-14b13397a0ca.png)

**Comment by wenche** [comment]
**Code**

By providing the URL to a story, you'll get an iframe with storybook content.
![Skjermbilde 2021-01-28 kl  13 42 56](https://user-images.githubusercontent.com/1568252/106140199-bcfe2080-616e-11eb-8d83-8efd555ae714.png)
In edit mode, you can resize the iframe to fit the content and choose whether the addons should be included or not. 

You can also add a code example or js/html/css code.
![Skjermbilde 2021-01-28 kl  13 44 54](https://user-images.githubusercontent.com/1568252/106140399-03ec1600-616f-11eb-8f4e-e9bc1dac0f69.png)

![Skjermbilde 2021-01-28 kl  13 43 47](https://user-images.githubusercontent.com/1568252/106140281-dacb8580-616e-11eb-9806-c8111ce21cb4.png)

To show source code or props table,[ the documentation recommends](https://zeroheight.com/3xlwst8/p/507ba7-storybook/t/052660) [Storybook Info Addon](https://www.npmjs.com/package/@storybook/addon-info). We should try that one.

**Comment by wenche** [comment]
**Adding text in general**

They provide a Medium like experience for adding content with save as you type. It's fairly easy to format text, and headers are automatically added to the side table of content.
![Skjermbilde 2021-01-28 kl  13 48 39](https://user-images.githubusercontent.com/1568252/106140863-9ee4f000-616f-11eb-89f4-ef64ffa81127.png)
![Skjermbilde 2021-01-28 kl  13 48 36](https://user-images.githubusercontent.com/1568252/106140866-9f7d8680-616f-11eb-81e4-c81802bc32da.png)
![Skjermbilde 2021-01-28 kl  13 48 27](https://user-images.githubusercontent.com/1568252/106140868-9f7d8680-616f-11eb-923c-6b00796cc6e1.png)

I copied plain markdown from the Storefront, worked pretty well but some misplaced empty headers due to several line breaks in our MDX files.

To add a table worked pretty well, had some issues with adding new images, but I think you'll get used to how you do it.
![Skjermbilde 2021-01-28 kl  13 51 50](https://user-images.githubusercontent.com/1568252/106141232-1adf3800-6170-11eb-90a8-930f3213c02e.png)

**Comment by wenche** [comment]
### First impression pros and cons

#### Pros
- Effective
- Pleasant to use
- Can copy'n paste existing content
- A lot more easy to add text and fix things
- Nice integrations for Figma and code. If not 100% perfect it's still a lot better than we have today
- Ready made components for pros and cons, tables, shortcut tiles and several other
- No need for manually updating menus and tocs - it just works
- Nice and modern editor view
- Good to have things in one place
- Interesting opportunities with icons, tokens, colors and typography. I think it will be a lot easier for our users
- Is tailored for style guides

#### Cons
- I think everybody on the team need a license, it will be very inefficient if only a few people can edit
- Some strange things with the Button component from Figma, the placeholder was slightly off
- We need to test out the code plugin to see how the props table act
- Limited options on changing styles. E.g. the front page with the image and header title
- You'll have to use it the way it's meant to be, if we think we need a lot of customizations it's probably not the right tool
-

**Comment by wenche** [comment]
We tried the suggested approach for propTable by using the [addon-info](https://www.npmjs.com/package/@storybook/addon-info) plugin. Out of the box it gives the following result
![Skjermbilde 2021-01-29 kl  11 26 58](https://user-images.githubusercontent.com/1568252/106264321-cc8c7080-6225-11eb-8f23-e713dbd39201.png)

According to the documentation, we are able to make it look better by using the configuration options. E.g. display it inline, remove unnecessary prop tables and create a custom better-looking table component.

**Comment by lucasveil** [comment]
Tested with design implementation and behaviour of updated component for [progress indicator](https://wenche-spike.zeroheight.com/styleguide/s/50799/p/87c09f-progress-indicators/b/57e9e7).

1) Zero height updates with the actual version of Figma and not the published one. So anyone pushing the "update figma file" in zero-height should check with the designers first,
2) Naming of component is a bit tricky when first implemented. Zero-hight takes the first of the component (in EDS case dark-theme true/false) so all component have to be renamed. The naming are then kept if figma is re-updated. 
3) Need of reorder the component for default and dark theme after implementation.

Implementation of design in zero-height will require some "first time" work (naming and styling) but updates will go smoothly.

**Comment by BirteThornquist** [comment]
We'll need to find another solution for video as video via Streams do not work (we tried to embed one) As we plan to use more how to-videos in the future, a smooth video solution would be nice.
A big pro for us is that we ourselves control our documentation updates. And it seems very easy to use. As Lucas already said there will be a "first time" job since the naming and order of the components does not follow the Figma logic when implemented to Zero-height. 
Summarized: we think the pros outweigh the cons.

**Comment by wenche** [comment]
On a team meeting at the end of last week we decided that we want to use Zeroheight for EDS documentation. Since we are such a small team we think it's much easier to write and maintain good documentation with a specialized tool like this. Next thing to do will be to document the findings from this issue in a pros and cons document #1115
