### ISSUE TITLE
Spike storybook as storefront

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1046]
Try to get an idea what it takes to move the content from the Storefront to the storybook to replace the storefront.

There are other component libraries using only Storybook for documentation, see e.g [Circuit](https://circuit.sumup.com/) and [Orbit](https://sg-orbit.netlify.app/)

- [x] What can be achieved by styling
- [x] Recreate the front page with graphics
- [x] Test Figma addon
- [x] Use Markdown for a page instead of the default storybook template

Merged into the branch `spike-storybook-as-storefront`

~Deployed to https://edsstoragedev.z16.web.core.windows.net/~

**Comment by wenche** [comment]
A simple Markdown approach, based on copy'n paste from original Storefront markdown files.
<img width="1788" alt="Skjermbilde 2021-01-19 kl  19 43 28" src="https://user-images.githubusercontent.com/1568252/105079741-20fa5800-5a90-11eb-8d94-03f9fd0d587f.png">
<img width="1016" alt="Skjermbilde 2021-01-19 kl  19 43 39" src="https://user-images.githubusercontent.com/1568252/105079748-248ddf00-5a90-11eb-899f-246ae9cc4981.png">
<img width="887" alt="Skjermbilde 2021-01-19 kl  19 43 49" src="https://user-images.githubusercontent.com/1568252/105079761-28b9fc80-5a90-11eb-833d-7b6990b6f80d.png">

**Comment by wenche** [comment]
1. impression: 
I like the flexibility it gains with placement of the props table and also that is generates unique urls based on each story, while we can place them where we want inside the text. We can also design and develop a few components for a better overview and structure of the page. E.g. an Figma link component, a better do's and don't component and so on.

As long as we only provides React component, I think it's easier for the end user to get an overview of the component by mixing text and live previews. But it might be harder to edit for non-developers as you don't want to accidentally break a code block. I might also provide a better overall impression of EDS since design and actual components  will feel more aligned.

I find it more error prone and harder to work with mdx instead of js. The tooling is lacking behind (automatic code formatting, ts support ++) and if something fails, it’s more difficult to debug. 

The pages will be quite long, but maybe we should remove some text?

**Comment by mimarz** [comment]
Great work!👍  @wenche 

Maybe we could also test the [figma-addon](https://medium.com/storybookjs/storybook-figma-addon-7a399f094a0a) for storybook?

**Comment by vnys** [comment]
Did you look into https://github.com/sumup-oss/circuit-ui? They’ve made some [custom storybook components](https://github.com/sumup-oss/circuit-ui/tree/canary/.storybook/components), which they use in [the stories](https://raw.githubusercontent.com/sumup-oss/circuit-ui/canary/src/components/Button/). Each component has a docs-file and tsx file, and the story-files are located in the component directory.

**Comment by wenche** [comment]
Nope, didn't use anything more custom yet, I wanted to just try the simple copy'n paste approach first to see how that worked (also since that would probably be the cheapest option)

**Comment by vnys** [comment]
Ok. But should we not also consider the potential of going all in with Storybook? If we only look at how easy it is to migrate the documentation, it becomes an unfair comparison with the other alternatives we’re spiking.

**Comment by wenche** [comment]
Ofc! But I'm not finished... :)

**Comment by vnys** [comment]
Ok, sorry – got a big confused there 😜

**Comment by wenche** [comment]
> Ok, sorry – got a big confused there 😜

Haha, you see the task list at the top? None of them are checked yet 😓

**Comment by wenche** [comment]
Update: Didn't bother to spend more time on the recreation of a page task. I'm sure we can do something similar as Circuit by linking mdx-files into the .tsx story if we want to. This might be easier to work with while documenting, however it's harder to have real React examples in between. We can also make our own components if we want to.

There are some work on some config issues to be able to import `mdx` files into `tsx`. But we'll be able to figure this out if we want to go in this direction.

The main pain point is the use of MDX and a less than ideal way of updating documentation. While it works technically, it's by far a more cumbersome and error prone process than a WYSIWYG type of editor. We need to make a decision here.

**Comment by wenche** [comment]
The Figma addon gives us a limited set of features. Even if it's[ mentioned that you can use design in Docs](https://medium.com/storybookjs/storybook-figma-addon-7a399f094a0a) the Design component is internal and not exported. In the design tab in the `Canvas` we can add a Figma design, but it's not possible to copy e.g. only the design for Text and Icon (light and dark mode) in the Text and icon story. You'll have all banner designs instead.

![Uploading Skjermbilde 2021-01-21 kl. 14.14.32.png…]()

**Comment by wenche** [comment]
Regarding styling it seems like the known limitations still is the case. Supports theming and we can do a couple of things with components and stuffs in the docs, but the menu and so on is not customizable.

**Comment by wenche** [comment]
![Skjermbilde 2021-01-21 kl  15 48 16](https://user-images.githubusercontent.com/1568252/105366850-1959c100-5c00-11eb-8323-3d532effa0b6.png)

It is possible to customize the index page. I don't know if it's possible to have fullscreen for only this page because the addon-docs documentation for MDX block is quite non-existing.

**Comment by pomfrida** [comment]
Can you force "Canvas" to be the main page, like we did in Menu?

**Comment by wenche** [comment]
> Can you force "Canvas" to be the main page, like we did in Menu?

Yes, that's possible

**Comment by pomfrida** [comment]
But I guess it's still centered, hmm.. Content has max-width 🤔
