### ISSUE TITLE
Single Select - Populate the whole list, not only the last selected item when reselecting

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#1065]
**Is your feature request related to a problem? Please describe.**

When a user selects one item in the list, this is the only value populated if the user decides to reselect looking for another value.

So if the user want to change value, she has to delete manually the selected value, in order to get the full list of items populated again...

![image](https://user-images.githubusercontent.com/22211376/105160175-33b47180-5b10-11eb-8f97-be5dbbc3af5f.png)
![image](https://user-images.githubusercontent.com/22211376/105160223-429b2400-5b10-11eb-8c5f-d1cfcf7d220b.png)

**Describe the solution you'd like**

After having selected a value, the user should get the whole list of items as default populated if she decides to look for another value.

**Describe alternatives you've considered**

Removing the selected value manually is cumbersome..., a slightly better alternative is an "x" delete option just to quickly clear the input field. However, the best alternative is that the whole list is populated always.

**Additional context**

**Comment by wenche** [comment]
Hi and thanks for your suggestion and engagement! 👏 

We are aware that some libraries for select/autocomplete/dropdowns/what ever you call it work the way you describe. However, we decided to use the same approach as the [native `Datalist`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) and Downshift's default behavior. This approach is explicit about the fact that the dropdown list is actually a filtered list from the input field, and that's why we think it makes sense to shrink the list.

If we were supposed to support both variants in EDS I'm afraid of the added complexity, not least in view of support for a11y. That's why we have agreed not to implement your feature request.

It this behavior is crucial for your use case, we would recommend you to use the EDS Native Select or go with MUI or react-select. We also have an [issue for decoupling TextField components](https://github.com/equinor/design-system/issues/1015). If this is prioritized, it will be easier for you to use EDS building blocks with Downshift's hooks and tailor the experience for your specific use case. 👍

**Comment by mimarz** [comment]
Re-opened due to popular demand
