### ISSUE TITLE
Research how to support model driven apps

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1078]
- [x] Create simple example in the EDS environment
- [x] Document procedure in issue

**Comment by pomfrida** [comment]
**Model-driven apps:**

In short, model-driven apps focuses on quickly adding already existing components to your app. These components are dashboards, forms, views, tables, charts etc. Unlike Canvas apps, you don't get much control over the app layout. Most of the UI and UX are predetermined for you. 


**Embed a Canvas app on a model-driven form:** 

With [embedded canvas apps](https://docs.microsoft.com/en-gb/powerapps/maker/model-driven-apps/embed-canvas-app-in-form), makers can bring the power of canvas apps to their model-driven forms. Using embedded canvas apps, you can easily create rich visual areas on a form and display data from a variety of sources right next to data from the Microsoft Dataverse.


**Use a [theme](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-themes-organization-branding) to create a custom look:**

This is what's the closest thing to a customised model-driven app I could find. However, this requires access we currently don't have in the organisation. Theming is used to enhance the app user interface, not drastically alter it. The theme colors are applied globally throughout your model-driven apps. Customising a theme includes enhancing these visual elements in the UI:
- Change navigation colors to create product branding.
- Adjust accent colors, such as hover or selection colors.
- Provide table-specific coloring.
- Logo. (Use an existing or add a new image file as a web resource.)
- Logo tooltip.
- Navigation bar color.
- Title text color.
- Selected link color.
- Hover link color.
- Legacy accent color (primary background for process controls).
- Default color for tables.
- Default custom tables color.
- Control fill color.
- Control border color.

These enhancements are very limited, and it's not enough for us to support EDS in model-driven apps. 

**Conclusion:**

We won't focus on supporting model-driven apps due to the current limitation it has. However, Rui from Microsoft said in a presentation that there's an ongoing work on exposing components both in Power App Portals and Model-driven apps. So hopefully when creating custom components for Canvas first, we can re-use them on some point later in model-driven apps.
