### ISSUE TITLE
Research how to support portal apps

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1080]
- [ ] Create simple example in the EDS environment
- [ ] Document procedure in issue

**Comment by pomfrida** [comment]
**Portals:**
In short, Power App Portals was made to quickly create a website and customise it with pages, layout, and content. Makers can reuse page designs through templates, add forms and views to display key data from Dataverse, and publish to users. Since it's web-based, CSS is used under the hood.

**Edit CSS for themes in Power Apps portal**
By default, bootstrap.min.css and theme.css files are available. You can edit the existing CSS files and upload new CSS files. When you upload a new CSS file, it will be available as a web file in the Portal Management app.
 
Portals use the Bootstrap front-end framework  to control the design and layout of the website.  You can take advantage of the customisation options that are provided by Bootstrap to tailor the theme in a way that’s applied consistently to the entire portal.
 
**Using CSS, where possible, has certain advantages:**
- CSS applies on load; it’s faster because you don’t have to wait for the document to finish loading.
- CSS is always on and continues to apply to the relevant elements, even if JavaScript changes the document structure and adds or removes the elements.
- For certain tasks that are related to an element’s visibility and responsive layout, CSS can be simpler to use than JavaScript, meaning less maintenance and less room for error.

**Comment by vnys** [comment]
So what that basically means is we would need a bootstrap theme to support Power App Portals 🤔 I wonder how that applies to components, assuming Microsoft is using Fluent UI components in the web portal. Have they added that as custom Bootstrap components?

**Comment by pomfrida** [comment]
Waiting for access in Power Apps Portals
