### ISSUE TITLE
Zeroheight - add design info for INPUTS

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1279]
- [x] **INPUTS**
- [x] Button
- [x] Search
- [x] Date/time picker
- [x] Select
- [x] Selection controls
- [x] Slider
- [x] Text field
- [x] Toggle button

**Comment by lucasveil** [comment]
@BirteThornquist @BeckyBrekke If you could have a look to the structure of the [button component](https://zeroheight.com/0b0c666ab/v/latest/p/9210bf-button/b/86826a). Be sure to be connected to your Equinor account so you can see the video. We need also to align with @mimarz to see what we can copy paste to the code tab.

**Comment by BirteThornquist** [comment]
Looking good @lucasveil! Great job! Can we just have the react component that the user could play with like in the story book, to view the different variations, instead of all the example images from Figma? But it's not always a 1:1 between Figma and React, so maybe it's best to keep it this way.... Maybe the background color of the dark theme example should be the dark theme background? And in the video, when you resize the button, maybe also resize the first one, just to demonstrate that the buttons should be the same width.

**Comment by BeckyBrekke** [comment]
Looks really good! The video example is great. I added the Storybook examples on the code page.

**Comment by lucasveil** [comment]
Have update the pages. After a talk with @mimarz , the interaction button is more complicated than expected. 

- Overview tab: shows the the "availability" of the component (all the variant with notification that dark theme and compact is only available in design), 

- Design tab: give all the infos on how if should be implemented with the do and don'ts 

- Code tab: updated with the same structure as the storybook

Any comments @BirteThornquist @BeckyBrekke @mimarz ? 
Keep in mind that this page will be asked for feedback from the design community :)

**Comment by BirteThornquist** [comment]
Looks really good @lucasveil!

**Comment by lucasveil** [comment]
Change the title of this issue from "Zeroheight - add design info for components" to "Zeroheight - add design info for INPUTS" so that each component have its own category. It will give us better overview on the status for each category.

**Comment by BeckyBrekke** [comment]
Looks good!! Get feedback from the meet the designers and then we can make a template out of this as a basis for the rest.

**Comment by lucasveil** [comment]
@BeckyBrekke  ready for review :)

**Comment by BeckyBrekke** [comment]
Reviewed and ready to go
