### ISSUE TITLE
Hover state in general for EDS

### ISSUE THREAD

**Issue by nilsml** [equinor/design-system#1426]

**Comment by BirteThornquist** [comment]
Lucas and I discussed the hover state for menu (will also affect drawer). As known we changed the weight of the menu title to 700 due to contrast issues using tabs. We got feedback from @mimarz and @pomfrida to instead use the same hover state as done for tables; use background color interactive/table header/fill hover but keep the text regular. See example below. We think both ways work. Unless there are other objectives we will go ahead and change it. Comments?
![Skjermbilde 2021-06-15 kl. 15.53.55.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/c8714042-7363-45e9-af93-485f98511fb8)

**Comment by mimarz** [comment]
Ok, so the suggestion is to change the menu hover to be the same as table now?

**Comment by pomfrida** [comment]
Agreed to discuss this in more detail in the near future. 

Both suggestions was implemented in this PR https://github.com/equinor/design-system/pull/1410; we landed on the same hover as in tables. This is easy to revert if we find out bold text on hover is a better solution.

**Comment by lucasveil** [comment]
As discussed with @mimarz and @BirteThornquist , **Menu title hover** has been update in the Design Tokens from bold to regular. In UI-User interface the component has been update with UI-background lighten to UI background medium.

**Comment by benteljones** [comment]
![Skjermbilde 2021-11-02 kl. 11.38.37.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/10e32d26-2368-4e0a-858d-ac2b09437271)

**Comment by benteljones** [comment]
Here is the link to the file in Figma: https://www.figma.com/file/MDkIHZdkMUw23EKI5HT83T/Bente?node-id=3%3A100

**Comment by oddvernes** [comment]
A potential way of doing bold without changing font weigth (causing layout-shift), and without using pseudo-element is with -webkit-text-stroke, which is non-standard, but supported by all browsers regardless.
`-webkit-text-stroke: 0.5px currentColor;` looks like this
![bilde](https://user-images.githubusercontent.com/4499531/140741945-d28ca4c4-aa6a-4b65-8574-4f465baa4136.png)

**Comment by mimarz** [comment]
Summary of meeting 10.11.21

- We still want bold text on hover as it provides the best readability
- @vnys will spike possible ways of applying bold text on hover until friday (#1684)
  - using `text-stroke` was deemed not feasible as it ruins the font
  - using "title-hack" works, but only for text. All our components accepts react nodes as children so any if anyone supplies anything other than text this approach would not work.
- Plan B is to keep it as it is with "Background/Medium" background color on hover (with pointer cursor)

**Comment by vnys** [comment]
Closed as this will be resolved in EDS 2.0
