### ISSUE TITLE
SingleSelect not working when using onChange.

### ISSUE THREAD

**Issue by wigsnes** [equinor/design-system#1455]
**Describe the bug**
We want to use a single select to either write like a textField or select element from list. The select part works fine, but when I want to get the input from the field by using the onChange prop the field stops working. It will not write in the field any more.

[https://codesandbox.io/s/elegant-poitras-0lv0u?file=/src/App.tsx](https://codesandbox.io/s/elegant-poitras-0lv0u?file=/src/App.tsx)

**Steps to reproduce the bug**

1. use onChange on SingleSelect.

**Expected behavior**

Work same as without onChange.

**Comment by wenche** [comment]
@wigsnes  Just a quick reply: Have you looked at the example for the [controlled component in the Storybook?]  (urhttps://eds-storybook-react.azurewebsites.net/?path=/docs/components-select-singleselect--controlledl) Maybe that approach might help you? That's at least one (simple) way of doing this. When you pass `onChange`, you are basically creating a controlled component, (this is how React form elements work) but  since you don't pass the value so you are in limbo state (aka can't write). Since the filter is based on that the `SingleSelect` controls the component, you should avoid to do it like this. :)

**Comment by pomfrida** [comment]
If you want to use an `onChange` here, you need to set `value={folderId}`. That should fix the limbo state in your sandbox.

**Comment by wigsnes** [comment]
> If you want to use an `onChange` here, you need to set `value={folderId}`. That should fix the limbo state in your sandbox.

It did not work at first, but it seems to be working consistent now, not sure why it would not work for me at first. Still this will stop the drop-down window to appear when typing, not such a problem for me. I can live with that, but if the items are declared outside of the function it looks like the SingleSelect will remove all other options. If you remove the selected option you only have the same item left. Redeclaring the items list inside the function will fix this, but I feel like this is not how it should work.

**Comment by pomfrida** [comment]
@wigsnes Yes this is clearly not the best approach, so you should definitely look at what @wenche mentioned before as we use the external Downshift library in our Selects.

**Comment by wigsnes** [comment]
I updated the codesandbox if you want to test it out, but for my use case It works fine at the moment, so you can call this issues closed.
