### ISSUE TITLE
Popover or Menu anchored to a Button is broken when wrapping the button in Tooltip

### ISSUE THREAD

**Issue by andbjer** [equinor/design-system#1496]
**Describe the bug**

When wrapping a `<Tooltip>` around a `<Button>` that has a `<Popover>`/`<Menu>` connected to it, the `Popover`/`Menu` won't open and you get this error: 

`Uncaught TypeError: Cannot read property 'contains' of null`

**Steps to reproduce the bug**

A reproduction of the bug can be found [here](https://codesandbox.io/s/eds-tooltip-bug-f9dvn?file=/src/App.tsx)

**Expected behavior**

That the `Popover`/`Menu` shows up.

**Specifications**

- Version: 0.13.0
- Browser: Google Chrome Version 91.0.4472.164
- OS: MacOS 11.4

**Additional context**

A possible [workaround](https://codesandbox.io/s/eds-tooltip-bug-workaround-gqlp1?file=/src/App.tsx) atm is to use `useState` instead of `useRef` and set the anchor element when the button is clicked.

**Comment by mimarz** [comment]
Thanks for reporting this! 

I don't think we have actually tested this combination, but this is most likely due to the `outsideClick` check we have in both components [here](https://github.com/equinor/design-system/blob/6fb617086e1df2326fc51ec9247c9e53cca4f7ff/libraries/core-react/src/components/Popover/Popover.tsx#L128) and [here](https://github.com/equinor/design-system/blob/6fb617086e1df2326fc51ec9247c9e53cca4f7ff/libraries/core-react/src/components/Menu/Menu.tsx#L59) 

We are preparing a release today with some updates and fixes, but we'll try to see if we can get a quick fix here or if you want to make a PR with the fix? Should be ok with just a check for if `anchorEl` is defined. 👼

**Comment by andbjer** [comment]
Yes, that seems to be the issue. I can make a PR with the fix :)

**Comment by andbjer** [comment]
Well, that doesn't really fix the issue. The error disappears but the `Popover`/`Menu` won't even open.
I can't spend any more time on this today and I'm leaving on vacation today, so it will be a little while before I can look into this again.

**Comment by mimarz** [comment]
> Well, that doesn't really fix the issue. The error disappears but the `Popover`/`Menu` won't even open.
> I can't spend any more time on this today and I'm leaving on vacation today, so it will be a little while before I can look into this again.

Ah, no problem! We'll have a look at it :) 
Thanks for your contribution and have a good vacation! ☀️ 👍
