### ISSUE TITLE
Date picker: show week numbers

### ISSUE THREAD

**Issue by einaren** [equinor/design-system#1503]
I see that you are working on a new Date picker. From what I could see in Figma, it does not seem like you plan to support week numbers. Is that something you can add?

**Comment by mimarz** [comment]
Thanks for requesting this feature request! 

Our designers are currently on vacation but I have added it to the list of feature-requests so you'll get a response after summer :)

**Comment by lucasveil** [comment]
Hi @einaren!
As per today we don't see the week numbers as a common feature in the date picker component since 
week numbers may vary according to your timezone. 
I suggest we take this issue in our backlog and prioritise it again if we get any new feature request related to week numbers.
In the meantime I have designed a rough draft (which is not approved by EDS) but may help you to in the design of your component: ![Screenshot 2021-10-01 at 09.54.18.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/c5eec5ed-71dc-440e-a0ea-92dd45d91a44)

**Comment by einaren** [comment]
Ok, thanks for letting me know! 

Ref "I suggest we take this issue in our backlog and prioritise it again if we get any new feature request related to week numbers."

-> does this mean that I'll get a notification in GitHub if this issue gets prioritized at a later stage?

**Comment by lucasveil** [comment]
That is correct @einaren :)

**Comment by BirteThornquist** [comment]
We will not introduce week numbers in the date picker due to complexities as mentioned above. Closing issue.
