### ISSUE TITLE
TextField component doesn't lose focus styling on blur if onBlur prop is provided

### ISSUE THREAD

**Issue by tfrausin** [equinor/design-system#1538]
**Describe the bug**

When passing a `onBlur` prop to the `TextField` component, the focus styling remains after the component loses focus.

**Steps to reproduce the bug**

1. Add a `onBlur` prop to `TextField`, `<TextField onBlur={something} />`

**Expected behavior**

Should drop focus styling on blur (component losing focus).

**Specifications**

- Version: 0.13.1
- Browser: Chrome Version 92.0.4515.159
- OS: macOS Version 11.4

**Additional context**

Code sandbox: https://codesandbox.io/s/eds-textfield-blur-qhsks?file=/src/App.js

**Comment by mimarz** [comment]
Thanks for reporting this! 

Can confirm this is a bug. Its due to the internal context using these for styling helper text+icon when input/textarea is focused. We are missing the composition for including external `onBlur` & `onFocus` handlers [here](https://github.com/equinor/design-system/blob/e5bafe80570f31161ca6f064e32ca0839c120715/libraries/core-react/src/components/TextField/Field.tsx#L195).

Note to self: Make composed functions for `onBlur` & `onFocus` with external callbacks.
