### ISSUE TITLE
Fix focus ring on components

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1705]
Chromium was recently updated for more complex outlines. https://chromium.googlesource.com/chromium/src/+/77a5954e1f52f5d9bbb9808e490fc9ae9233ec2d 

One improvement was that `border-radius` now works on outline. Since this change, we might need to adjust the outline offset on some of our components (and Figma?) Button focus frame is now very hard to see due to short offset.

Edit:
![image](https://user-images.githubusercontent.com/1070981/142149978-643336a4-fe07-43ab-874f-513f977f2343.png)
![image](https://user-images.githubusercontent.com/1070981/142150061-12ebcca7-7eed-4047-a560-cae06c65b885.png)

**Comment by oddvernes** [comment]
I feel like 1px thickness of this is not helping, I have to lean in to see it on my laptop monitor

**Comment by vnys** [comment]
Bente and I concluded that the problem is bigger than just fixing the focus-ring on the button-component, as there are inconsistencies with how we indicate focus across components. This is not critical, so I’ve made a new issue – “Make focus-indicators more uniform across components” (#1733) – and added it to the “Conforming Components” epic (#1598).
