### ISSUE TITLE
Add disclaimer page about Zeroheight limitations

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1727]
As we cannot use our own best practises in Zeroheight, we should add a disclaimer page that highlights the issues that are problematic so that our users know that it’s out of our control.

**Comment by BeckyBrekke** [comment]
Email that we sent to zeroheight: 
Hi again Tim, 
 
We sent this list into the support team, and they said they have prioritized the first issue and hopefully would have a fix in place in about 2 weeks depending on how it goes. That is promising! We hope to move back to zeroheight after the fix is in place, with some redesigning on our side to overcome some of the current limitations.
1.	More secure handling of custom domain names
2.	User friendly URLs
3.	Better mobile experience (no refresh to see the “mobile styleguide”)
4.	Improved accessibility and layout options on the front page
Regarding improved accessibility, we have guidelines in place in our design system that have a high focus on accessibility, and we want our users to be able to visit our documentation site and see these guidelines implemented and that is not possible in zeroheight today. We need to lead by example. Hopefully based on your growth these issues will be addressed in the near future. Until then we will add a disclaimer page saying our design system documentation site does not fully reflect our guidelines and does not meet our minimum accessibility standards since we use a third party service. 
 
Here are some of the similar issues we found on your forum, and have added my comments there. I will add or comment to other issues we see as well.  
Responsive size on cover image - zeroheight forum
 
Customizing Cover Page by making elements optional - zeroheight forum
 
Hide release name on cover page - zeroheight forum
 
Possibility to add "alt" text to images and components - zeroheight forum

**Comment by vnys** [comment]
Postponed until after the workshop (May 10–11 2022)

**Comment by akvam** [comment]
Since Zerohight has been with us for a long time now, and we have not done this, I suggest to close this issue. Any comments @BeckyBrekke , @vnys ?

**Comment by mimarz** [comment]
Speak now or forever hold your peace
