### ISSUE TITLE
Make focus-indicators more uniform across components

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1733]
Both clickbounds and focus-indicators vary greatly across components, as can be seen in the screenshot. Most components have dotted outlines, but not all – and the spacing between the components and the focus-indicators are inconsistent. 

![image](https://user-images.githubusercontent.com/2081882/143854426-e80ed0cd-4cff-413f-8c0b-5cb41188cabc.png)

**Comment by vnys** [comment]
https://w3c.github.io/wcag/techniques/css/C41

**Comment by mimarz** [comment]
We've had long discussions about this all year, in short we've landed on
* Input having a solid line is intended
* "Ghost" components should have a focus which matches the hover/clickbound box
* "Contained/filled" have the focus frame with a offset

Focus frame being a dotted line.

With the changes to rendering focus, we've noticed that the outline offset became to small & outline line to thin.

**Comment by oddvernes** [comment]
the focus frame currently is 1px dashed. Just changing it to 2px makes a big difference, and then maybe increase the offset from 2px to 3px

**Comment by vnys** [comment]
Let’s discuss this issue in the backlog meeting on Wednesday

**Comment by oddvernes** [comment]
After discussion with @lucasveil and @mimarz we have decided to decouple the focus-width from figma and instead hard code it in the figma broker to 2px. I will go over each component with `focus-visible` and test plus adjust offset where needed so we get a consistently visible focus ring

**Comment by oddvernes** [comment]
Components with focus-visible (that uses dashed outline) have been updated to fetch outline-width from token, and token have been updated to 2px, but for now this is hardcoded in figma-broker. 
In the future we may have a 'second-source-of-truth' config for styles figma does not support or otherwise cannot be fetched from figma.

Radio/Checkbox: offset reduced by 1px so focus-ring doesn't touch label, table borders:
![bilde](https://user-images.githubusercontent.com/4499531/155340873-815b97e7-885e-4133-8b45-0a2b6b26478b.png)
![bilde](https://user-images.githubusercontent.com/4499531/155341071-75c9ad10-ff6e-4f68-b4ef-318ccabdf589.png)

Button/Chip/Slider: increase offset by 1px to make where focus is it easier to spot when scanning:
![bilde](https://user-images.githubusercontent.com/4499531/155343036-80e7fee0-964b-4717-a915-a4ce72f4cc70.png)
![bilde](https://user-images.githubusercontent.com/4499531/155343157-f3319778-f2ea-4372-bd0f-e38fb69fbd70.png)
![bilde](https://user-images.githubusercontent.com/4499531/155343288-ac9cba53-b04f-4b45-88fe-690c09ac66d2.png)

Ghost_icon button: offset -2px so it is inset to clickbounds and fit inside table
![bilde](https://user-images.githubusercontent.com/4499531/155343825-89655f06-e6c9-4029-adf4-6b102f9326f4.png)
