### ISSUE TITLE
A design bug in Table, Input Read only?

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#1832]

**Comment by benteljones** [comment]
Figma, in the library:
When I select Input (Data Display, Table) and I try to shift to Read only (State), (in both theme, light and dark) another selection appears: Monospaced Numeric. If I select Variant to Input again, it goes back to Enabled (State, Tertiary text color) again. I can’t select Read only (Primary text color). Hmmm ... ?

**Comment by BirteThornquist** [comment]
![Skjermbilde 2022-01-03 kl. 10.03.01.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/44c7ca94-3b40-4361-81b5-10176171941d)

**Comment by benteljones** [comment]
![Skjermbilde 2022-01-03 kl. 10.03.31.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/93411e14-d46d-4c6d-aaf3-5750e7d525fb)

**Comment by BirteThornquist** [comment]
The problem here is that we have states not shared among all the instances. For the input cell the state "Read only" is not used, but since it is in use for other instances in the group it will be listed and possible to choose but will go to the instance that use Read only. A fix will be to use "Read only" instead of "Filled input only" for the input. But we face the same problem with "Error/active resting only" since these states only exist for the input instances. Do we really need all these states? We have the new Table Data grid anyways.... What do you think @lucasveil and @benteljones ?

**Comment by benteljones** [comment]
Shall we take a look at together it at our UI/UX meeting on Monday? @BirteThornquist  and @lucasveil

**Comment by BirteThornquist** [comment]
We decided to leave this as is. A restructure/renaming would be breaking change. None of our users have filed this as a problem, and the Data Grid will be used for input edit in tables going forward. Closing the issue.
