### ISSUE TITLE
Input validation does not work correctly on TextField component

### ISSUE THREAD

**Issue by v3gard** [equinor/design-system#1972]
The TextField component (in a number context) allows some basic input validation when using the arrows to increase/decrease the current value. However, you are still allowed to enter a random value outside the specified range.

**Side issue**: The component uses the browser tooltip (in the browser local language) and not the EDS tooltip.

|Chrome on Windows 10 (Norwegian)|Chrome on Windows 11 (English)|
|-----------------------|--------------------------|
|![image](https://user-images.githubusercontent.com/343078/153411969-38649da5-c94d-4ea0-9f7c-c3cd6118a61c.png)|![image](https://user-images.githubusercontent.com/343078/153412066-ac0ed473-84dd-4d97-84c5-fff574edf0bb.png)|

Is it the responsibility of the frontend app that uses the component to handle this, or should the component itself sanitize the inputs as there is some input validation present? 

(Note that proper use of input sanitation should be done once more in the backend of the application that uses this, but this is outside the scope of this issue.)

**Steps to reproduce the bug**

Define a Textfield like this:
```
<TextField
    id={someId}
    max={10}
    min={1}
    onChange={(event: ChangeEvent<HTMLInputElement>) => setScore(event.target.valueAsNumber)}
    type="number"
    value={category.score?.toString() ?? ""}
/>
```

**Expected behavior**

When input validation is specified on the component with `min` and `max`, I expect the component to also handle user input and show an error if the value exceeds the range.

Regarding tooltip: I also expect the EDS tooltip to be used and not the browser native tooltip.

**Specifications**

- Version: 0.17.0
- Browser: Chrome
- OS:  Windows 10/11

**Comment by oddvernes** [comment]
Hi!

By putting `type="number"` you activate some native behaviour in the browser and this includes some rudimentary validation, which that tooltip with error message is a part of. This is expected behaviour and we have no power to control this. You could further add css-selectors :valid and :invalid to change the styles of the component based on this validation. 

We do not include any custom validation in this component and leave this up to the users, since it would be impossible for us to cover all use cases. Users should implement their own validation, or use a third party solution [such as React hook form](https://react-hook-form.com/), which there is an example of in our[ storybook](https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-textfield--example-with-react-hook-form).

The error message should be put in the `helperText` prop and variant set to 'error' when there is a validation error. 
Also when implementing custom validation, I think leaving the type prop to its default (text) is better so you avoid this native behaviour. If you still want numeric keyboard to pop up on touch devices, it is possible to set `inputMode="numeric"` on the input 🙂

**Comment by v3gard** [comment]
Thanks for the feedback! Perhaps it would be beneficial to add an example and clause about input validation is the developer's responsibility in the storybook. That way, developers won't be confused about how input validation should be implemented and who's responsibility it is.

**Comment by oddvernes** [comment]
Good point! We already have an example in the Textfield stories but it is not explained well. for now I will update the description of this story 👍
