### ISSUE TITLE
Export new focus state token from Figma and update components to use the new token

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1977]
Related to #1415

A new focus token has been implemented and released in Figma
Ghost buttons and Selection control has now been updated.

Edit: 
* Run figmabroker to update tokens
* Update components (mentioned above) to use the new focus token

**Comment by oddvernes** [comment]
As it turns out this new token does not follow the standard naming scheme of compact/default so it is discarded by the script. But from what I can see, the outline-offset on various focus rings are set manually anyway in the local component tokens and not fetched from figma. Furthermore, it looks like ghost_icon and selectioon controls had their focus frame adjusted to 48x48 by Frida 5 months ago already  ¯\_(ツ)_/¯

**Comment by lucasveil** [comment]
@lucasveil needs to update documentation

**Comment by mimarz** [comment]
Changing this to work needed to be done in Figma as these tokens are not used in code due to nature of components needing different values for focus frame to fit correctly.

**Comment by akvam** [comment]
This will now be handled in code since we will not have focus token in EDS 2.0.
