### ISSUE TITLE
Components documentation list

### ISSUE THREAD

**Issue by laliq** [equinor/design-system#2156]
**For Storybook**

- [x] AppLauncher #718  
- [x] Accordion #423 
- [x] Avatar #2250 
- [x] Banner #424 
- [x] Breadcrumbs #439 
- [x] Button #431 
- [x] Card #443 
- [x] Checkbox #2257 
- [x] Chip #438 
- [x] Dialog #436 
- [x] Divider #435 
- [x] Icon #446 
- [x] Input #2262 
- [x] Label #2265 
- [x] List #429 
- [x] Menu #450
- [x] Pagination #425 
- [x] Paper #2266 
- [x] Popover #442 
- [x] Progress #434 
- [x] Radio #2274
- [x] Scrim #447 
- [x] Serach #449 
- [x] Select #420 
- [x] SideSheet #448 
- [x] Slider #433 
- [x] Snackbar #451 
- [x] Switch #2279
- [x] Table #440 
- [x] TableOfContent #428 
- [x] Tabs #2284
- [x] TextField #441 
- [x] Textarea #2291
- [x] Tooltip #444 
- [x] TopBar #437 
- [x] Typography #452 
- [x] Update ARIA links #2240 
- [x] Typos #2306

**Comment by martalalik** [comment]
**For Zeroheight**

- _Avatar_ - it does't exists in [Components](https://eds.equinor.com/0b0c666ab/p/99b362-components) section, but there is documentation in [Foundation](https://eds.equinor.com/0b0c666ab/p/96f1b1-image-placeholder/b/85d6bc) section. Maybe there is a reason for it 🤔 ?
- _Autocomplete_ - there is no documentation
- __

**Comment by BeckyBrekke** [comment]
**For Zeroheight**

- [ ] Avatar - it does't exists in [Components](https://eds.equinor.com/0b0c666ab/p/99b362-components) section, but there is documentation in [Foundation](https://eds.equinor.com/0b0c666ab/p/96f1b1-image-placeholder/b/85d6bc) section. Maybe there is a reason for it 🤔 ?
- [ ]  Autocomplete - there is no documentation.
- [ ]  Banner - got additional description &`Text` example is wrong is a repetition of `Text and Icon` example.
- [ ]  Breadcrumbs - lack of links to rest of the examples.
- [ ]  Button - i would link `Icon button` & `Progress button` & `Full width` examples.
- [ ]  Card - got additional description & i would link `With media` & `With divider` examples.
- [ ]  Chip - lack of links to rest of the examples.
- [ ]  Dialog - lack of links to rest of the examples & the `Demo` view it doesn’t show well the example after triggering the Dialog.
- [ ]  Divider - got additional description & lack of links to rest of the examples.
- [ ]  Menu - link is broken & i would link `Complex ` example.
- [ ]  Paper - it does't exists in [Components](https://eds.equinor.com/0b0c666ab/p/99b362-components) section, but there is documentation in [Foundation](https://eds.equinor.com/0b0c666ab/p/568642-elevation/b/790b54) as `Elevation`. Not sure if we need listed as a component 🤔 .  
- [ ]  Popover - i would link `With Tooltip ` example.
- [ ]  Progress:Dot - link is broken.
- [ ]  Scrim - link is broken & got additional description.
- [ ]  Search - link is broken & lack of links to rest of the examples.
- [ ]  Select:Native - link is broken.
- [ ]  Side Sheet - - link is broken & lack of links to rest of the examples & got additional description.
- [ ]  Slider -  lack of links to rest of the examples.
- [ ]  Snackbar - got additional description.
- [ ]  Table - got additional description.
- [ ]  TableOfContent - link is broken.
- [ ]  Tabs - 


- [ ]  TextField -  lack of links to rest of the examples. The examples from [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A51467) in [Zeroheight](https://eds.equinor.com/0b0c666ab/p/77e7d5-text-field/b/86826a) are misleading because the `helper text` is overlapping with icon and another text.

**Comment by lucasveil** [comment]
Reviewed from design team written in bold

- [ ] Avatar - it does't exists in [Components](https://eds.equinor.com/0b0c666ab/p/99b362-components) section, but there is documentation in [Foundation](https://eds.equinor.com/0b0c666ab/p/96f1b1-image-placeholder/b/85d6bc) section. Maybe there is a reason for it 🤔 ?
**Avatar is a token and doesn't exist as a component**
- [ ]Autocomplete - there is no documentation.
**Autocomplete is not set in design component**
 - [ ]Banner - got additional description &Text example is wrong is a repetition of Text and Icon example.
**Text alone is now deleted and added the compact version**
 - [ ]Breadcrumbs - lack of links to rest of the examples.
 **Added text "More examples available in the code tab"**
 - [ ]Button - i would link Icon button & Progress button & Full width examples.
**Icon button is showed in the variant section. Full wisth button have been added to the demo**
 - [ ]Card - got additional description & i would link With media & With divider examples.
 **Card with divider have been added**
 - [ ]Chip - lack of links to rest of the examples.
**Added text "More examples available in the code tab"**
 - [ ]Dialog - lack of links to rest of the examples & the Demo view it doesn’t show well the example after triggering the Dialog.
**Added text "More examples available in the code tab"**
 - [ ]Divider - got additional description & lack of links to rest of the examples.
 **Added text "More examples available in the code tab"**
 - [ ]Menu - link is broken & i would link Complex example.
 **Link is fixed and added compact to the demo**
 - [ ]Paper - it does't exists in [Components](https://eds.equinor.com/0b0c666ab/p/99b362-components) section, but there is documentation in [Foundation](https://eds.equinor.com/0b0c666ab/p/568642-elevation/b/790b54) as Elevation. Not sure if we need listed as a component 🤔 .
 **If understood weel paper is a tokenm only for code, this one doesn't exist in figma. The one we use is "sidesheet, card" in tokens"
 - [ ]Popover - i would link With Tooltip example.
 **Added text "More examples available in the code tab"**
 - [ ]Scrim - link is broken & got additional description.
 **Link and description are fixed **
 - [ ]Search - link is broken & lack of links to rest of the examples.
 - [ ]Side Sheet - - link is broken & lack of links to rest of the examples & got additional description.
 - [ ]Slider - lack of links to rest of the examples.
 - [ ]Snackbar - got additional description.
 - [ ]Table - got additional description.
 - [ ]Tabs - the link might broke after the merge, maybe link more examples? And the most confusing is this: Tabs have a minimum width of Spacer/16 - Medium on each side of the label. we took it away from the storybook.
 - [ ]TextField - lack of links to rest of the examples. The examples from [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A51467) in [Zeroheight](https://eds.equinor.com/0b0c666ab/p/77e7d5-text-field/b/86826a) are misleading because the helper text is overlapping with icon and another text.

**Comment by martalalik** [comment]
This one is deprecated @Hjaf

**Comment by martalalik** [comment]
[Image placeholder](https://eds.equinor.com/0b0c666ab/p/96f1b1-image-placeholder/b/8997eb) in `code` the link is broken.

**Comment by mimarz** [comment]
> [Image placeholder](https://eds.equinor.com/0b0c666ab/p/96f1b1-image-placeholder/b/8997eb) in `code` the link is broken.

We don't have a placeholder for images in code as its some specific for Figma, so maybe remove the code tab from this? @lucasveil

**Comment by lucasveil** [comment]
Agreed @mimarz The code tab is now made as hidden

**Comment by BeckyBrekke** [comment]
Looks good @lucasveil . I just the sentence about "more examples available in code" to search, side sheet and tabs. Do you want to check anything else @martalalik or can we publish the changes?

**Comment by martalalik** [comment]
Closing this one, we can continue with #2332
