### ISSUE TITLE
Update Lists component

### ISSUE THREAD

**Issue by laliq** [equinor/design-system#2163]
The component looks like need an update.
Look into ➡️  [Material Design](https://material.io/components/lists#usage) as a reference.
Investigate the purpose of the element and how it is used by developers.

**Comment by akvam** [comment]
@martalalik can you please clarify the intention behind this US?

**Comment by martalalik** [comment]
This issue came out when i was working on dev documentation. 
My intention was to see if there is a need for expanding  `List` component, to be more complex, as is presented in [Material Design](https://material.io/components/lists#usage).
But at this point i haven’t pop into any requests from developers that would propose changes in this component. I guess we can close it @akvam .

**Comment by BirteThornquist** [comment]
As this is not based on a user need and is pretty vague I'm closing this issue.
