### ISSUE TITLE
⬆️ Upgrade storybook 7.0 (previously mdx 2)

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2514]
MDX has been updated to 2.0 with big changes: https://mdxjs.com/blog/v2/

Storybook will eventually move to mdx-2, migration guide for experimental support: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#opt-in-mdx2-support

**Comment by oddvernes** [comment]
Is this done, since it is listed as a blocker for react 18?

**Comment by mimarz** [comment]
> Is this done, since it is listed as a blocker for react 18?

Its not done, but had to be done after #2285 as it had upgrades and changes to Storybook config.

Should be good to do the migration now.

**Comment by oddvernes** [comment]
From what I can see, the experimental mdx2 support in storybook 6.5 is still problematic and I am not the only one getting[ styling issues](https://github.com/storybookjs/storybook/issues/18383). They say it will work better out of the box with storybook 7, So I think perhaps we should just wait for that and upgrade to storybook 7 whenever that is stable. 

Things to note when upgrading: 
mdx2 does not support html comments (`<!--...-->`) and should be replaced with {/*...*/}
`<strong>word</strong> ` must be replaced with **word**
It also complained about newline here:
![bilde](https://user-images.githubusercontent.com/4499531/215985679-7d0be9b2-14b2-4c1c-b689-1aed2a8d8f9e.png)
But hopefully that is fixed with the 7.0 implementation

**Comment by oddvernes** [comment]
Storybook 7.0 is now released. We'll probably wait for at least 7.1.0 (currently in alpha)
