### ISSUE TITLE
As a designer I need default spacing and placement rules.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#259]
Blocked by #632 

Need to document distance between components.  

Guidelines where component should be placed.  

In Figma: In Example project adda new File in Example Project named as Patterns (with multiple pages)  

Should buttons be placed to left or right (guideline not an absolute rule)  

Align to right in dialog boxes 

Align to left in Pages 

 For Compact: Include spacing rules between components. This US does not cover making the individual  components compact. 

Add documentation to StoreFront if needed.

**Comment by benkeq** [comment]
@lucasveil
I started laying out a [template](https://www.figma.com/file/BleNV0tE9Aopz3asajjNkA/Bendik-test?node-id=2184%3A0) for us so that we keep the page clean and clear. If you check "Bendik test" under 'Patterns' you will find some examples used in a different project. We can probably use some of that as inspiration.

**Comment by benkeq** [comment]
You may have looked at it already, but can you approve or decline [Spacings](https://www.figma.com/file/WUqA45HIHyZCkGkITNkljE/?node-id=1%3A2) and [Placement and order](https://www.figma.com/file/WUqA45HIHyZCkGkITNkljE/?node-id=55%3A0)? @lucasveil
