### ISSUE TITLE
As a designer I would like to have alternative heading sizes on Side Sheet

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#263]
Comments from workshop: 
Designer kan velge mellom headingtyper, men må ta en avsjekk på avstander og alignment når andre enn H1 bruker.

**Comment by vnys** [comment]
I think we should differentiate between header levels and font-sizes here, or people will get it wrong and choose a header-level based on what font-size it’s styled with instead of it’s order in the document outline. We need a proper discussion on how we work with typography in the EDS, there are already some issue about that somewhere.

**Comment by lucasveil** [comment]
We need to define also how many variations of text size we want to implement.

**Comment by BirteThornquist** [comment]
This will be solved by #784 #794. Can we close this issue @benteljones @trondeide ?
