### ISSUE TITLE
Table component for Beta

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2647]
**Table** is a component that we want to test in EDS 2.0. We used Data grid table as a starting point and added auto-layout and proprieties in order to be aligned with all new component in EDS 2.0.

**Comment by lucasveil** [comment]
After common review, i added the hover variant and adjusted the auto layout labels.
Ready for review @benteljones @BirteThornquist before we implement colors and space tokens

**Comment by benteljones** [comment]
Naming: Component 1 and Table. Change to cell & header in the design menu, component name?

Should the icon on the right side stick to the right edge? If not they would be placed differently, not aligned vertically, because of different text lengths. 

When I type some text, the box, shape, stops after a while, but the icon and text continue. 🤔 ![Skjermbilde 2022-11-09 kl. 15.40.33.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/6d306197-0f45-4bc0-81fb-d3b92bc04a55)

**Comment by lucasveil** [comment]
Naming is now up to date, good catch :) @benteljones 
When you resize cell or header it misses its "hug" attribute and is set to fixed. It is the same for the button component. I should investigate to see if there is a solution for this.
The right icon should be next to the label and not to sticked to the right edge other woae it can be confusing in the table.

**Comment by benteljones** [comment]
When there is only an icon on the header and not in the cells, a close contact between the text and the icon on the right will make sense. It's quite possible that it should be placed consecutively after the text anyway. We should still take a final check on how it will turn out since we are opening up using icons in the cells as well. And in some cases both the icon on the left and the right; for example both a symbol and unit of measurement. Do we have any examples from users using these variants, or should we make one as a final check-out? Examples with icons in header and cell, both variants? How does it look in an overall context? How will it be with the variant input with icons?

**Comment by lucasveil** [comment]
Impossible to have autolayout + constraints for table. We need to choose either the icon is right aligned or that the text scales

**Comment by trondeide** [comment]
I believe Ive got a solution that could work.
