### ISSUE TITLE
Tooltip around disabled button is not shown in Chrome (works in Firefox)

### ISSUE THREAD

**Issue by AndreasPresthammer** [equinor/design-system#2724]
Repro: https://codesandbox.io/s/dazzling-rosalind-28qeuh?file=/src/App.tsx

```
<Tooltip title="I'm disabled. Chrome users can't see this">
  <Button disabled={true}>I'm disabled. You can't click me</Button>
</Tooltip>
```

Tooltip on the above button won't be shown in Chrome. This seem to be caused by Chrome not firing events for disabled elements. See https://stackoverflow.com/a/18113961. Firefix does fire these events though.

A workaround can be to wrap the children of the Tooltip in a `<div>` as suggested in the linked Stackoverflow above. Although as you see in the repro link the positioning of the tooltip might need some work.

- Version:  "@equinor/eds-core-react": "0.28.0",
- Browser: Chrome 108.0.5359.125 (doesn't work) / Firefox 107.0 (works)
- OS: Windows 11

**Comment by oddvernes** [comment]
We will update storybook tooltip with our recommended solution (use `aria-disabled` instead of `disabled` for buttons with tooltip, especially if the tooltip explains why the button is disabled. If you instead really want to use the wrapper element method, I suggest using a `<span>`, as a div is a block element that will take full width of available space 👍
