### ISSUE TITLE
Subtitle field for Accordion component

### ISSUE THREAD

**Issue by sebastianvitterso** [equinor/design-system#2729]
**Is your feature request related to a problem? Please describe.**
In our project, we're going to use accordions to make hide 15 forms in 15 `Accordion.Item`'s. We're going to have to implement some custom functionality for this, because we want to be able to see a "short status"/summary of the inside state without opening each accordion.

**Describe the solution you'd like**

We had our UX'er (@AnnKinge) come up with a design (which we have currently implemented into our application), which looks something like this: 
![image](https://user-images.githubusercontent.com/37065184/212859261-06cedbdc-ac4d-4f9e-9f67-e9221d612b39.png)

**Additional context**
As mentioned, we have (for now) implemented the entire Accordion-component as a clone of yours, and added the desired functionality, but that's also the only difference between ours and yours. If you were to add this functionality, we could go back to using EDS maintained code, which would be nice for us.

**Comment by oddvernes** [comment]
Instead of cloning the whole component, could you possibly do something like this? (I'm using style-tag here so you see whats going on but of course you can use class or styled-components override as well) 
![bilde](https://user-images.githubusercontent.com/4499531/212870104-c7996b15-1ba6-44bb-9845-8cbf39c871a9.png)
result: 
![bilde](https://user-images.githubusercontent.com/4499531/212870545-951bc26d-be52-48ce-bc49-e79191a54b9a.png)

**Comment by sebastianvitterso** [comment]
That's clever, I thought about doing something like this, but I just assumed that Accordion.Header wanted a `string` input. I should've just tried!

**Comment by oddvernes** [comment]
No problem! I didn't test this thuroughly with large amounts of text etc. but I think this should work, with just some tweaking to conform with the design. I'll close this issue as resolved 👍
