### ISSUE TITLE
Have option to choose 24hour time instead of AM/PM in datepicker

### ISSUE THREAD

**Issue by Eddasol** [equinor/design-system#2746]
**Is your feature request related to a problem? Please describe.**
When using datepicker the time is chosen as either AM or PM

**Describe the solution you'd like**
Most non-americans aren't used to using AM/PM. It would be better if its possible to have a configuration allowing to choose between AM/PM or 0-24hour. Personally I consider 24hour as better as the chance of confusion and errors is lower.

**Comment by oddvernes** [comment]
If you are using `Textfield` with `type="time"` or `"datetime-local"` this is native browser ui and not something we control in eds. It depends on what browser is used, browser settings and operating system settings which time format ends up being displayed. I know with `Edge` you are pretty much stuck with am/pm because it is some sort of policy setting that users can't change (?). 

We do have a `Timepicker` component in `@equinor/eds-lab-react` which is a community contribution and not really maintained by us, but it might work for some people in some cases.

**Comment by oddvernes** [comment]
Closing issue as it is not solvable by us
