### ISSUE TITLE
Textarea not found in '@equinor/eds-core-react

### ISSUE THREAD

**Issue by nimsilva** [equinor/design-system#2828]
**Describe the bug**

I'm trying to use `Textarea` as described in the documentation:

```
import { Textarea } from '@equinor/eds-core-react'

<Textarea />
```

But I get the following error:

> export 'Textarea' (imported as 'Textarea') was not found in '@equinor/eds-core-react'

**Steps to reproduce the bug**

1. Import Textarea into a file as described by the documentation: import { Textarea } from '@equinor/eds-core-react
2. Try to use <Textarea />

**Expected behavior**

Textarea should be displayed with no compilation errors

**Specifications**

- Version: 0.28.0
- Browser: Chrome latest version
- OS: Windows 10

**Additional context**
![image](https://user-images.githubusercontent.com/88738856/227215424-1ebc4c97-1bd4-4e3b-92d6-811ff1b9cf5f.png)
![image](https://user-images.githubusercontent.com/88738856/227215566-66fed198-9bdc-4e6d-a6c2-8149e34967a6.png)
![image](https://user-images.githubusercontent.com/88738856/227215628-da51ed1d-e8bc-447c-9d3a-03a50ce25fd6.png)

**Comment by oddvernes** [comment]
Hi! Our storybook documentation is wrong 🤦‍♂.  `Textarea` is an internal component not directly accessible to users. It is used in `TextField` when `multiline` prop is added (which is then a Textarea with additional built in functionality such as `label`, `helpertext` etc).

If you have a need for `Textarea` specifically without the `Inputwrapper` in order to have extra flexibility we can consider making `Textarea` importable as we have done with `Input`. 

Regardless we need to update our documentation because right now i think it is too easy for people to be confused by the difference between Input/textarea and `TextField` (TextField should be used in most cases)

**Comment by nimsilva** [comment]
Thank you for the answer. I will use `TextField` instead  😊
