### ISSUE TITLE
Fix inconsistent styling of Accordion Items when they are components

### ISSUE THREAD

**Issue by TormodNy** [equinor/design-system#2865]
**Describe the bug**
When I am using `Accordion` the `Accordion.Item`s has content and functionality such that it is nice to make separate components for them. However, doing this makes the styling differ slightly from having them directly as children of the `Accordion`. In the demo linked below you can see that the borders between `Accordion.Item`s are thicker and the chevron switches to the other side.
https://codesandbox.io/s/2023-05-05-eds-accordion-styling-evi939?file=/src/App.tsx

**Expected behavior**

The `Accordion.Item`s should look identical when used in a component vs when they are direct children under the `Accordion` component.

**Specifications**

- Version: 0.31.1
- Browser: Google Chrome
- OS: Windows

**Additional context**
https://codesandbox.io/s/2023-05-05-eds-accordion-styling-evi939?file=/src/App.tsx

**Comment by oddvernes** [comment]
I see something funky is happening when item is a wrapped function, we'll have someone investigate this 👍

**Comment by denektenina** [comment]
Hi! 

Thanks for your question. I looked into it, and the reason this is happening is because when you create the `<AccordionItem>` inside your function component `<AccordItem>`, you are inserting a level between `<Accordion>` and `<AccordionItem>.` This is intercepting a vital connection between the two.

**If you want some more details (if not, skip to the solution)**
When you build an Accordion tree with an `<Accordion>` that has `<AccordionItem>` as a child, `<Accordion>` iterates through its children, and adds some props to them (an id, its own `headerLevel` and `chevronPosition`).  `<AccordionItem>` receives these props and uses them when rendering its own children. It will for instance create some new ids using the id it received and send the `headerLevel` and `chevronPosition` further down the three to its own children. 

In your code, the nearest child of `<Accordion>` is not `<AccordionItem>`, but `<AccordItem>`, your own function component. This function receives the props from `<Accordion>`, but it doesn't use them, and creates `<AccordionItem>`s that doesn't receive the props it needs from `<Accordion>`. Because of this, `<AccordionItem>` is missing some vital information needed to render the component correctly.

**The solution**
You need to acknowledge the props you are receiving from `<Accordion>` and pass them down to `<AccordionItem>` like this:

```
function AccordItem({ num, ...props }: AccordItemProps) {
  return (
    <Accordion.Item {...props}>
      <Accordion.Header>
        <Accordion.HeaderTitle>Header {num}</Accordion.HeaderTitle>
      </Accordion.Header>
      <Accordion.Panel>Content {num}</Accordion.Panel>
    </Accordion.Item>
  );
}
```

Let me know if you have any more questions.

**Comment by TormodNy** [comment]
Thank you! Doing as you suggested works perfectly 🥳
