### ISSUE TITLE
Autocomplete drop down does not check for room under it on first render.

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/design-system#2918]
**Describe the bug**

When using the Autocomplete component on small screens/windows the position of the drop down does not position it self correctly.
To get it to position itself the user first has to open it scroll down and up again, after that the positioning is correct. If the user refreshed the page the problem reoccurs. 

**Steps to reproduce the bug**

1. Position an autocomplete component so that it is at the bottom of the screen on refresh.
2. Refresh page.
3. Click on autocomplete.

**Expected behavior**

Expect the drop down menu to position itself at "top-start" when there is not enough room under it.

**Specifications**

- Version: 0.31.1
- Browser: Chrome Version 114.0.5735.106 
- OS: Ubuntu 22.04

**Additional context**

![Autocomplete bug demonstration](https://github.com/equinor/design-system/assets/25079611/fa93423a-6cf3-43c0-ab6d-4f4e92aea4ff)

**Comment by oddvernes** [comment]
I believe this was serendipitously fixed by the latest update of floating-ui. [Storybook-dev](https://s478stedsstorybookdev.z16.web.core.windows.net/?path=/docs/inputs-autocomplete--docs) (up to date) [storybook prod](https://storybook.eds.equinor.com/?path=/docs/inputs-autocomplete--docs) (not updated)
