### ISSUE TITLE
"arrow_down_small" and "arrow_up_small" missing in eds-icons package

### ISSUE THREAD

**Issue by siglar** [equinor/design-system#3039]
Icons "arrow_down_small" and "arrow_up_small" are missing in the NPM package.

As seen in the [Storybook](https://storybook.eds.equinor.com/?path=/docs/icons-preview--docs):
![image](https://github.com/equinor/design-system/assets/3383006/79485140-2592-409b-9af8-df0d56fb3450)

**Comment by oddvernes** [comment]
Hello! Some icons have "small" versions, but they are not seperate icons, they are inside the icon object under `icon.sizes.small`. These are used internally by the Icon component when size is set to 16 and 18 to prevent "fuzzyness". They should probably not be included in the storybook listing since it will lead to this sort of confusion 😅
