### ISSUE TITLE
PersonPicker component is hidden behind Dialog popup

### ISSUE THREAD

**Issue by Jonathanio123** [equinor/design-system#3056]
**Describe the bug**
PersonPicker is hidden behind Dialog popup, see screenshot

**To Reproduce**
There isn't a way to reproduce in the app in question as you need certain permissions. 
However, I created a code sketch on how it looks in the code
```TypeScript

      <Dialog ...>
        <Dialog.Header>
          ... Title
        </Dialog.Header>
        <Dialog.Content>
          <PersonPicker .../>
          <NativeSelect ...>
        </Dialog.Content>
        <Dialog.Actions>
        ... Buttons
        </Dialog.Actions>
      </Dialog>

```

**Screenshots**
![image](https://github.com/equinor/design-system/assets/73334350/b669e0e8-c983-4b09-af95-593dfa53aac9)

**Specifications**
 - Version: 0.32.4
 - OS: Windows 11
 - Browser: Edge Version 116.0.1938.81 (Official build) (64-bit)
 - fusion-components version: 2.10.8

**Additional context**
We are in the process of updating eds core react to the latest version. I've tried manually changing zindex on different properties. This may be a fusion component problem, if it is I'll close this issue.

**Comment by oddvernes** [comment]
Hello! Z-index will not work here, as `Dialog` now uses native `<dialog>` element which renders on top of the html in a seperate layer. The fusion component used inside here is presumably using a  react portal which only creates a div at the bottom of `<body>` positioned absolutely. Unfortunately the fusion component will need to be updated to support non-portal rendering, as rendering the content inside the Dialog is required for all floating components (all the eds floating components have the option to render inline + we use a hook from eds-utils to autodetect if it is inside a dialog to force no-portal mode). Once the `popover` attribute is supported by all major browser we will start using that for our floaters as well since that too put the content in the top layer.
