### ISSUE TITLE
Accordion: headerLevel not working

### ISSUE THREAD

**Issue by AndrejNikolicEq** [equinor/design-system#3205]
**Describe the bug**

In Accordion component [Storybook](https://storybook.eds.equinor.com/?path=/docs/surfaces-accordion--docs) headerLevel is not making any changes. Also tested in app.

**Steps to reproduce the bug**

1. Go to EDS Storybook
2. Go to Accordion
3. Try changing headerLevel in controls

**Expected behavior**

When changing headerLevel in controls or changing them when using component, heading should also change.

**Specifications**

- Version: 0.35.1
- Browser: Microsoft Edge
- OS: macOS Sonoma 14.2

**Comment by oddvernes** [comment]
Hello! The headerlevel prop is purely for semantic purposes. Since we don't know the context the accordion is used in, it is up to the developer downstream to pick the correct headerlevel. An accordion under a h2 paragraph should be h3 for example. What I guess you expect, and we havent explained well enough in the documentation, is that the header style remains the same regardless. I will update the description for the prop to explain this better! 👍
