### ISSUE TITLE
💄 Slider: test suggested design improvements

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3223]
- Remove arrow, move tooltip down accordingly.
- Make option to show tootlip below

See if this works for a column of range sliders where toltip is set to "always show"

**Comment by vnys** [comment]
@BirteThornquist, @benteljones and @marinalinn will have a look at it. @BirteThornquist will call for a meeting.

**Comment by BirteThornquist** [comment]
Today, we did a review of the enhancements proposed for the slider component. The following changes have been approved and will be implemented:

- The slider value will now be displayed within a tooltip box rather than below the slider line. This is already implemented in code.
- The colour of the tooltip box and text will align with other input components for consistency.
- The tooltip's size will be scaled down to prevent placement conflicts with the slider label.
- The tooltip will offer options to display above or below the slider line, as well as the choice to show continuously or only on hover.
- Text size adjustments for improved readability. 

A separate issue has been created to ensure the Figma slider component reflects these enhancements accurately.
