### ISSUE TITLE
Hover on buttons are misaligned

### ISSUE THREAD

**Issue by mhelv** [equinor/design-system#3383]
**Describe the bug**

When hovering almost all of the buttons it might be hovered 6pixels of the target on right side but 0px on the top. I can understand it's nice to 

![bug](https://github.com/equinor/design-system/assets/118977037/f354a437-dade-4d34-9b56-5d275901ae01)

**Steps to reproduce the bug**

1. Go to https://storybook.eds.equinor.com/index.html?path=/docs/inputs-button-button--docs
2. Hover over Icon button or Basic button
3. The hover now shows 8px of from the right, but 0px of from the top

**Expected behavior**

Hover either 0px or the same on all directions.

**Specifications**

- Version: 0.36.1
- Browser: Chrome
- OS: Windows

**How to fix**

Remove Height and Width CSS in the ::after on all buttons. alternatively add an "auto" onto them. 
PS. Width and Height has no reason to be hard coded on an ::after.

**Comment by oddvernes** [comment]
Thanks for the report! The width and height on the absolutely positioned ::after is to create a "clickbound" that complies with wcag rules without making the button itself gigantic. But the offsets are currently wrong so it is off-center. As a first step we need to fix that, but we also should consider reducing the size from 48x48 to 44x44 since the [wcag 2.2 rules for for this has been relaxed](https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced)
