### ISSUE TITLE
Present the typography proposal with Amplify

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3388]
We had to made some updates to the typography component when we saw how it worked in Amplify’s components. The most significant change is that the UI (non-aligned to grid) is now also rounded up to the nearest 12 and centered vertically. And that “On grid” is now a boolean option in `UI`, `Body` and `Header`. We have also discussed two different types of headers, inside and outside components, where the difference is the font (Inter/Equinor).

**Comment by marinalinn** [comment]
We had a meeting with Amplify team last Friday (April 19) where we presented:

**1. Fonts: Inter + Equinor.** We explained the current proposal for mobile apps and the reasons for it, and a potential usage on web apps letting them to analyze the case and giving us feedback about it in the next meeting. 
**2. Alignment: Optical alignment, Icons and Baseline grid.** Explanation of current concepts to understand in order to explain the new proposal for typography and spacing.
**3. Typography and spacing foundations: applied to Amplify.** Showed them examples on how the proposal would look in their products and asked for feedback. 
**4. Density: Spacious, Comfortable and Compact.** Showed them how density would look in their products and received feedback on how valuable is for them. 
**5. Roadmap:** Expectations aligned and processes communicated by sharing our roadmap with them.
**6. Final note: Comparison components between design systems.** A quick update about the comparison file and future expectations for better collaboration.

**Action points:**

- We will be present in the next biweekly designers Amplify meeting.
- Definitions for spacing and typography Container level.
- Exploration about density: following their feedback it seems that in some cases is necessary to apply the density only to spacing and in other cases to spacing and typography. Decisions about it to present in the meeting.
- Amplify team members will send us Figma files with products or views they think are relevant to test. Those will be presented on the next meeting.
