### ISSUE TITLE
Present the typography proposal with Echo

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3389]
Owner: @marinalinn

**Comment by marinalinn** [comment]
We had a meeting with Echo team today (Tuesday 30) where we presented:

1. Fonts: Inter + Equinor. We explained the current proposal for mobile apps and the reasons for it, and a potential usage on web apps letting them to analyze the case and giving us feedback about it in the next meeting.
2. Alignment: Optical alignment, Icons and Baseline grid. Explanation of current concepts to understand in order to explain the new proposal for typography and spacing.
3. Typography and spacing foundations: applied to Amplify. Showed them examples on how the proposal would look in their products and asked for feedback.
4. Density: Spacious, Comfortable and Compact. Showed them how density would look in their products and received feedback on how valuable is for them.
5. Roadmap: Expectations aligned and processes communicated by sharing our roadmap with them.
6. Final note: Comparison components between design systems. A quick update about the comparison file and future expectations for better collaboration.

We also needed from them a better introduction to what Echo offer to their users, main actions and pain points, devices where the products are available and so on.

Figma file [here.](https://www.figma.com/file/eLkiLRhwFfpCGl2AROSrG3/Test-file?type=design&node-id=0%3A1&mode=design&t=r9dvPiFYxiNcCa4G-1)

**Action points:**

- Definitions for spacing and typography Container level.
- Amplify team members will send us Figma files with products or views they think are relevant to test. Those will be presented on the next meeting.
-  In the next meeting we will discuss about the differences between web app and mobile for Echo. 
 - Casper will share files showing differences between mobile and tablets ✅
 - Check access to Echo following feedback from the team.
 - Check with Digital field workers more about the equipment.
- Book a another meeting to include Echo on the process with EDSM.

**Comment by marinalinn** [comment]
[Digital field workers ](https://statoilsrm.sharepoint.com/sites/DigitalFieldWorkerHUB)
