### ISSUE TITLE
Optional "clear" button in the TextField component

### ISSUE THREAD

**Issue by o-jorgensen** [equinor/design-system#3398]
In the Autocomplete component, the `hideClearButton` property lets us enable users to clear the contents of the field (i.e. selected value), which often comes in handy.

When working on other input types such as date, the [current recommendation](https://storybook.eds.equinor.com/?path=/docs/inputs-textfield--docs#date-and-time) is to use `<TextField type="date">` for cross-browser consistency and accessibility. However, this component doesn't seem to have any options for clearing the contents, and we would need to make custom functions whenever needed.

Having the `hideClearButton` property for all(?) input components would make things more consistent for developers and users.

**Comment by oddvernes** [comment]
Hello! The `hideClearButton` prop is actually to optionally _remove_ the clear button in `Autocomplete` where the button otherwise serves a specific purpose (clearing a potentially large amount of selections quickly). There are currently no plans to add this functionality into `TextField`, but it is something we can take into consideration. I know we have this in `Search` but  that does mean adding more state handling into the component + some [hacky workaround](https://github.com/equinor/design-system/blob/develop/packages/eds-utils/src/utils/setReactInputValue.ts)

As for datepicker, our next upcoming release introduces a brand new `Datepicker` and `DateRangePicker` (which does have a clear button) See a preview of it [here](https://s478stedsstorybookdev.z16.web.core.windows.net/?path=/docs/inputs-dates-datepicker--docs) and [here](https://s478stedsstorybookdev.z16.web.core.windows.net/?path=/docs/inputs-dates-daterangepicker--docs)!

**Comment by o-jorgensen** [comment]
Interestingly enough, the primary reason for this feature request was a case for selecting a date range and a simple to clear it - so the upcoming `DateRangePicker` seems like a perfect match 🥳 

Thanks for the good news!

PS. I realize that the mentioned prop _removes_ the clear button, but I confused myself somewhere in my choice of words there 😅

**Comment by BirteThornquist** [comment]
We will not implement "clear button" in TextField component at this time as we don't see the need in a regular text input field where it is easy to remove the text.
