### ISSUE TITLE
Allow non-string as Banner.Message children prop

### ISSUE THREAD

**Issue by AndreasPresthammer** [equinor/design-system#3666]
The Banner.Message currently only accept string as children, and wraps the string inside a <Typography> element. We would like the ability to express richer styling-structure (lists, links etc) in the Banner.Message.children. Would it be possible to change the Banner.Message to accept ReactNode  as children instead of just string, and not have it nested inside a Typography.

**Describe the solution you'd like**

I want to be able to express things like this:
```
<Banner>
  <Banner.Message>
    <List>
      <List.Item>My first thing</List.Item>
      <List.Item>My second item</List.Item>
    </List>
  </Banner.Message>
</Banner>
```
Today the above give typescript errors, and also the list would get wrapped inside a `Typography` element.

**Describe alternatives you've considered**

Today we can force non string elements into the Banner.Message.children, but the non-string element would still get nested inside `Typography`.

**Comment by AndreasPresthammer** [comment]
Ref https://equinor.slack.com/archives/CJT20H1B9/p1730197485058199

**Comment by FredrikMWold** [comment]
What about add a new prop boolean to `<Banner.Message />` called `asChild`

if asChild is fasle then `<Banner.Message />` will wrap the children in a `Typography`
if asChild is true then then  `<Banner.Message />` will return the children

Then the user would be able to use any kind of element they want.

**Comment by AndreasPresthammer** [comment]
The most "forgiving" way might be to check if props.children is a string, and then wrap it in `Typography`, otherwise just render props.children.

This would make this change non-breaking for existing code. The negative would be the (maybe) surprising special handling of the 'string' case.

**Comment by FredrikMWold** [comment]
The issue with checking if `children` is a string and only wrapping it in that case is that it could create a breaking change.

Since the styling properties of `Typography` are inherited, users might already rely on the styles provided by the `Typography` component. Conditionally applying the wrapper could disrupt these inherited styles for existing implementations.

Using an `asChild` prop would avoid this issue, allowing developers to opt into the behavior only when needed and preserving backward compatibility for all other cases.

**Comment by AndreasPresthammer** [comment]
> Another solution could be to not use `Banner.Message`. Looking at the implementation, `Banner.Message` only wraps `children` in a `Typography` component and sets the variant to `body_long`, so you could directly use your own component in place of `Banner.Message` if needed.

This might well be a solution we could explore. But I guess the downside of this is that we are walking somewhat outside the established API of the Banner component, and thus might break in the future due to unreleted changes. Might be a an OK price to pay for now.

**Comment by oddvernes** [comment]
Given that `Banner.Message` is literally just a `Typography` with nothing added I would agree that you should just not use it if you need html content. Just make sure to replace it with an outermost div since the grid expects 1-3 children (`grid-template-columns: ${$hasIcon ? 'min-content 1fr auto' : '1fr auto'};`)
