### ISSUE TITLE
Use Docz

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#474]
As part of the effort to fill in developer documentation in the Storefront, we need a component playground with examples and proptables. We’ll use Docz for that, which is built on top of Gatsby, which is what we’re already using in the storefront. To make it as easy as possible to upgrade to new versions of Docz in the future we should avoid custom solutions where possible and do things the Docz way. That means for example using Theme UI for styling where we don’t use EDS components, and adding route fields to frontmatter. 

- [x] Move pages and add frontmatter (@vnys) 
- [x] Style the sidebar like the navigation drawer (@vnys)
- [x] Use [Page component ](https://www.docz.site/docs/creating-your-themes#using-documents-settings)for table of content, tabs  (@wenche)
- [x] Add component status overview component
- [x]  Add remaining styles from[ layout.css](https://github.com/equinor/design-system/blob/storefront/apps/storefront/src/components/layout.css)

**Comment by wenche** [comment]
The concept of Page component had some very confusing and incorrect documentation, but according to ComponentProvider's type declaration, Layout.js will also receive the `doc` object. That's why we did the overall layout things with toc and tabs with component shadowing of [Layout](https://github.com/equinor/design-system/pull/400/commits/8b474295244c9d4714c7be6f2b65d8dd971fbf40#diff-e2da14d2d19aacd0ee3a9cdba20c85ec) and [MainContainer](https://github.com/equinor/design-system/pull/400/commits/8b474295244c9d4714c7be6f2b65d8dd971fbf40#diff-189f3dc19a76e4e1d8f8fea76634a55e).

**Comment by wenche** [comment]
We are currently using a mix of theme-ui sx-feature as used by Docz Gatsby theme, styled-components and even some plain CSS for styling. Even if our EDS components use Styled-components, we would probably benefit from using sx instead of styled-components for pure Storefront styles and this will also make it easier to provide a dark theme in the storefront later on.
