### ISSUE TITLE
Icon size inside button

### ISSUE THREAD

**Issue by bratli** [equinor/design-system#516]
**Describe the bug**

It is not possible to set the iconsize inside a button. This is set as '24px' by EDS, and is not possible to change even when setting size property on icon.

**Steps to reproduce the bug**

1. Create a button with an EDS icon
2. View button - see that size is 24px (height and width)
3. Set size property of EDS icon to 16
4. See that this has no effect on icon. Looking at inline styling in console on browser, it says that height and width is 16. However, this is overwritten by some svg styling that is 24px height and width,
(when looking at code in node_modules in our app, see core-react.umd.js on line 1857)

**Expected behavior**

In the documentation for button with icon, size=16 is passed to the EDS icon (even when it doesn't seem to have an effect in the component shown in the documentation either). Would expect it to be possible to set the size since we have a prop for this, and looks like it should be possible in the documentation.

**Specifications**

- Version: 0.5.1
- Browser: Chrome
- OS: 

**Additional context**

Add any other context or screenshots about the bug.

**Comment by pomfrida** [comment]
Due to icon readability we had to bump up the icon size in buttons from 16px to 24px in v0.4.0. We currently do not support size change but will leave this in the backlog as a feature request so we can look at it when there's time for it. The expected behaviour from the documentation is simply just something we forgot to remove after the size change.

**Comment by nilsml** [comment]
We will create a new issue to put in the backlog that better explains what needs to be done. #1290
