### ISSUE TITLE
Provide an alternative to Icon.add

### ISSUE THREAD

**Issue by trylle** [equinor/design-system#584]
**Is your feature request related to a problem? Please describe.**

Normally, when we use icons in our components, we will import the specific icon and use it directly, e.g.

```jsx
import AssignmentIcon from '@material-ui/icons/Assignment';

<AssignmentIcon />
```

EDS requires pre-registering the icons via `Icon.add`, which means we have to maintain this list in our project separately from the component that uses it, and doesn't feel particularly developer-friendly.

**Describe the solution you'd like**

I would like to avoid using `Icon.add`. The simplest option that occurs to me is to have a data property to Icon where we can pass the object imported from eds-icons, e.g.

```jsx
import { save } from '@equinor/eds-icons';

<Icon data={save} />
```

Alternatively. provide pre-defined components for each icon, like material-ui. The latter option seems like a lot of work unless it was automatically generated.

**Describe alternatives you've considered**

Currently, we have just written a wrapper for Icon that automatically invokes Icon.add for us via hooks.

**Comment by mimarz** [comment]
Good suggestions! 👍

We had a long discussions about how to do the `Icon` component api during development (#177) We landed on the Font Awesome approach because most of the times you have a set of icons you use for application and thats it. Although everyone have different preferences and use-cases that might need a different approach.

We are leaning more towards the `data` prop approach, as this would make it easier to compose the icon as needed to match any use-case or preference when consuming `<Icon>`
