### ISSUE TITLE
Conform compound types export

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#821]
Make sure we export the types for component and not the compound component type.

**Wrong:** 
```
import { Popover as BaseComponent } from './Popover'
import { PopoverTitle } from './PopoverTitle'
import { PopoverAnchor } from './PopoverAnchor'
import { PopoverContent } from './PopoverContent'

type PopoverProps = typeof BaseComponent & {
  PopoverTitle: typeof PopoverTitle
  PopoverAnchor: typeof PopoverAnchor
  PopoverContent: typeof PopoverContent
}

const Popover = BaseComponent as PopoverProps

Popover.PopoverTitle = PopoverTitle
Popover.PopoverAnchor = PopoverAnchor
Popover.PopoverContent = PopoverContent

export { Popover, PopoverProps }
```

**Correct:**
```
import { Popover as BaseComponent, PopoverProps } from './Popover'
import { PopoverTitle } from './PopoverTitle'
import { PopoverAnchor } from './PopoverAnchor'
import { PopoverContent } from './PopoverContent'

type PopoverCompoundProps = typeof BaseComponent & {
  PopoverTitle: typeof PopoverTitle
  PopoverAnchor: typeof PopoverAnchor
  PopoverContent: typeof PopoverContent
}

const Popover = BaseComponent as PopoverCompoundProps

Popover.PopoverTitle = PopoverTitle
Popover.PopoverAnchor = PopoverAnchor
Popover.PopoverContent = PopoverContent

export { Popover }
export type { PopoverProps }

```

**Comment by vnys** [comment]
Are we sure about that? Because the type of `<Popover>` in the example above is not `PopoverProps` when it’s re-exported, it’s `PopoverCompoundProps`. So this may work in the story where we import the props explicitly, but that’s not how the component will be used in the wild. 

Using Dialog as an example since that’s what I’m working with: 

**The props imported explicitely:**
![image](https://user-images.githubusercontent.com/2081882/98143380-4fbd5500-1ec9-11eb-826d-be15c950831a.png)

**The actual type of `<Dialog>`:**
![image](https://user-images.githubusercontent.com/2081882/98143598-96ab4a80-1ec9-11eb-8f70-16f0e0df0bff.png)

**Comment by wenche** [comment]
When it comes to Typescript we are not sure about anything 🤪  But this was an honest attempt to make it work with args, and we even discussed it with somebody outside the team. 

Everything would have been so much easier with `import {Dialog, Title} from '@equinor/eds-core-react'` :)

**Comment by vnys** [comment]
Maybe, but it wouldn’t be obvious then that `<Title />` belongs inside `<Dialog />`. But my point in this case is that in the example of `<Dialog />` above, the type of `<Dialog />` is `DialogCompoundProps` – so what do we achieve then by exporting the original types _without_ the subcomponents? What problem does that solve? And would it make any difference to add the sub components inside `<Dialog />` instead of adding them in the re-export in `index.ts`? Then at least there would only exist one set of `<Dialog />` types instead of two.

**Comment by vnys** [comment]
We use destructuring as a pattern to get the subcomponents, but what if you don’t? This is also a perfectly valid way to use the `<Dialog />` component for example: 

```jsx
<Dialog>
  <Dialog.Title>Some title</Dialog.Title>
  <Dialog.CustomContent>Some content</Dialog.CustomContent>
  <Dialog.Actions>
    <Button>Ok</Button>
  </Dialog.Actions>
</Dialog>
```

Wouldn’t you expect VS Code to show you `Title` as a type on `<Dialog />` when you type `<Dialog.T…`?

**Comment by vnys** [comment]
Here’s [an old Kent C. Todds post about compound components](https://kentcdodds.com/blog/compound-components-with-react-hooks), and here’s [an implementation in Typescript](https://blog.diondreedwards.com/react-compound-component-using-typescript). Not sure if it helps or just adds to the confusion.

**Comment by vnys** [comment]
Never mind the comment about destructuring, you would still get intellisense without Typescript for that…
