### ISSUE TITLE
Storybook prop tables for some components are not working as expected

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#841]
Should look into it and fix them when we have time:
- [ ] Menu
- [ ] TextField

**Comment by wenche** [comment]
I think this is pretty important to fix for the Menu.

Currently we don't give props for the Menu component so it's complicated to know how it's supposed to work. Doesn't make things easier that the Menu component is a complex one either 🙈 

I think this happens because of the MenuProvider in the `index.ts` file.

```
const MenuWrapper: FC<MenuProps> = ({ children, ...rest }) => (
  <MenuProvider>
    <BaseMenu {...rest}>{children}</BaseMenu>
  </MenuProvider>
)

const Menu = MenuWrapper as MenuType
```
Storybook renders the props table like this, resulting in no props for the actual Menu component:
![Skjermbilde 2021-01-26 kl  15 00 12](https://user-images.githubusercontent.com/1568252/105855237-27388900-5fe8-11eb-844b-06e804387f0e.png)

**Comment by mimarz** [comment]
Closing this issue as these work now
