### ISSUE TITLE
eds-core-react is not tree-shaking as expected

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#854]
Test shows that a single import from eds-core-react imports the whole library. Should use tree-shaking to avoid this.

**Comment by pomfrida** [comment]
Build results after only importing `Button`:
![Screenshot 2020-11-09 at 13 18 06](https://user-images.githubusercontent.com/31915755/98544107-c70d3300-2293-11eb-9717-a0dcdd9786cd.png)

**Comment by mimarz** [comment]
Did some more testing here, and its due to typescript importing `core-react` using the `commonjs` bundle (which is what typescript operates with internally). `commonjs` modules as we know are not tree-shakeable....

Other libraries have solved this by providing named explicit named paths for components. Such as [Material-UI](https://material-ui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking)

**Comment by mimarz** [comment]
Closing this issue as we have a seperate issue for named paths #1043
