### ISSUE TITLE
Storybook crashes when changing icon name

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#955]
**Describe the bug**

As [mentioned on Slack](https://equinor.slack.com/archives/CJT20H1B9/p1607340075219400) – when a user change the name value on the[ icon examples](https://eds-storybook-react.azurewebsites.net/?path=/docs/components-icon--icon-examples) the page crashes.

**Steps to reproduce the bug**

1. Go to https://eds-storybook-react.azurewebsites.net/?path=/docs/components-icon--icon-examples
2. Change the value of the name property

**Expected behavior**

It should show the icon you put into the name field

**Specifications**

- Version: n/a
- Browser: Microsoft Edge
- OS: macOS Big Sur

**Comment by mimarz** [comment]
This is due to our check if provided icon name exists in our library [here](https://github.com/equinor/design-system/blob/7ac17da28b7d98dba9649944c51e8779cd6ce5e3/libraries/core-react/src/components/Icon/Icon.tsx#L84). 

We had weird errors getting this option to work with Storybooks select option in props table for some reason during [conversion of story](https://github.com/equinor/design-system/pull/812). Might work now since we have updated Storybook since then.
