### ISSUE TITLE
Power BI EDS template - additional color examples

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#980]
Some customers need to make charts with 4 - 8 colors that should be easy to distinguish between. 

This US covers to extend the template for this use case. 

Some users have asked for color options with completely different hues that can be easy to tell apart from other. Others have reported that they use the cross highlighting feature which dims the colors of the unselected items on the chart and can be confusing. 
Good to have different examples based on use case. Need for dark theme and light theme. 
Will work with Birte on this and can use Bente too. 
Other users have asked for colors of the same intensity - today color number 2 is more intense and stands out more. 

3 alternatives - brand - similiar colors, brand very different and maybe something totally different for other cases
Notes are located in this [OneNote](https://statoilsrm.sharepoint.com/sites/Designsystem/_layouts/OneNote.aspx?id=%2Fsites%2FDesignsystem%2FShared%20Documents%2FGeneral%2FPower%20BI%2FExamples%2FPower%20BI%20examples&wd=target%28Color%20schemes.one%7CC461E3B1-30B9-4CD3-AE59-C6112EFAADA9%2F%29

**Comment by BeckyBrekke** [comment]
In the process of talking with users and gathering information about this. Link to the OneNote in the description. Had a talk with Lucas about it. Him and Birte can help but this needs to be prioritized along with other design tasks. Agreed I would continue the research for now. Bente in IOC has also said she could be available for help as needed.

**Comment by BeckyBrekke** [comment]
Been collecting different examples in the OneNote (link above). Need some help with the actual colors when people have time.

**Comment by BeckyBrekke** [comment]
We had a kickoff meting about this this week, me, Lucas, Birte and Bente.
We decided to make a new issue just for the design work - since it is Power BI independent. Lucas and Birte would start looking at that. We need some data visualization color palette options and guidelines on when and why to use which one - one with colors in the same color family, one with very distinguishable colors, maybe one for the different products (oil, gas, etc)

**Comment by BeckyBrekke** [comment]
Moving this to in progress since I have started to implement and test colors with Birte. [Here is the Power BI report](https://app.powerbi.com/groups/me/apps/2fc55c86-4da0-46d9-b0c3-5ad31c3aee82/reports/65e80d24-de94-4c49-82d3-2ac11a49f987/ReportSection3e40bbd48c971131664b?ctid=3aa4a235-b6e2-48d5-9195-7fcf05b459b0) where I am testing.

**Comment by BeckyBrekke** [comment]
Testing this out with some users. Christophe has given feedback and will get feedback from some others.

**Comment by BirteThornquist** [comment]
@BeckyBrekke  I have outlined an example page using a new selection of colors [here](https://www.figma.com/file/dCtGxSjiufV5C6YcXSs3MD/Birte-test?node-id=565%3A871)

**Comment by BeckyBrekke** [comment]
Worked with Birte on this last week - pinpointed what wasn't working and what did work, and she would try and come up with some suggestions for what was NOT working.

**Comment by BeckyBrekke** [comment]
Birte and I worked on this before the summer and agreed to give advice and examples with explanations where we can, and try not have one suggestion that fits every need. 
Have started working on this after the summer and will update what we have.
